export const Colors = {
  light: {
    background: "#F9F5FF",
    surface: "#F3E8FF",
    surfaceAlt: "#E9D5FF",
    border: "#D8B4FE",
    button: "#A855F7",
    subtitle: "#C084FC",
    title: "#6A0DAD",
    subtitleDark: "#48176dff",
    link: "#4C1D95",
    text: "#1F1F1F",
    subtext: "#444",
    placeholder: "#888",
    inputBorder: "#999",
    white: "#FFF",
  },
  dark: {
    background: "#1A0E2A",
    surface: "#2A153D",
    surfaceAlt: "#3B1D54",
    border: "#5B21B6",
    primaryLight: "#7C3AED",
    primary: "#6A0DAD",
    primaryDark: "#581C87",
    primaryDarker: "#4C1D95",
    text: "#FFF",
    subtitle: "#CCC",
    placeholder: "#AAA",
    inputBorder: "#555",
    white: "#FFF",
  },
};
